version: '3'
services:
  api:
    command: sh dev.sh
    build: .
    image: instagramtools/api
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    depends_on:
      - postgres
    links:
      - postgres:postgres
    environment:
      - FLASK_ENV=development
      - FLASK_APP=server
      - DEBUG=True
      - SECRET_KEY=5(15ds+i2+%ik6z&!yer+ga9m=e%jcqiz_5wszg)r-z!2--b2d
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_SERVICE=postgres
      - DB_PORT=5432
      - PATH_TO_SSH_KEY=tk
      - SSH_PORT=tk
      - IP=tk
      - SECURITY_PASSWORD_SALT=tk
    env_file:
      - .env/.mail.env
  postgres:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres

volumes:
  db_data: